test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

vaults3:
  service: VaultS3
  access_key_id: <%= Rails.application.credentials.dig(:vaults3, Rails.env, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:vaults3, Rails.env, :secret_access_key) %>
  bucket: <%= Rails.application.credentials.dig(:vaults3, Rails.env, :bucket) %>
  region: us-east-1
  endpoint: http://10.100.11.11:9000
  force_path_style: true
